# 파이토치 기초
- 참고:파이썬, 딥러닝, 파이토치/이경택, 방성수, 안상준 저
- http://github.com/Justin-A/DeepLearning101


In [1]:
import torch

## 텐서: ndarray와 같은 용도의 숫자를 담고 있는 어레이를 말함

# Scalar
- 0차원 텐서

In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])    
print(scalar2)

tensor([3.])


In [4]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


- 메소드 add(), sub() 등을 제공한다

In [8]:
torch.add(scalar1, scalar2)

tensor([4.])

In [9]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [10]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [11]:
torch.div(scalar1, scalar2)

tensor([0.3333])

# Vector: 1차원 텐서

In [13]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [14]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [15]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [16]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [17]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [18]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [19]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [20]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

### 항목별 곱셈 및 나눗셈

In [21]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [22]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

### 매트릭스 곱셈
- 내적이라고도 부른다

In [23]:
torch.dot(vector1, vector2)

tensor(32.)

# Matrix: 2차원 어레이

In [24]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [26]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [27]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [28]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [29]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [30]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [31]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [32]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [33]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

### 매트릭스 곱셈

In [34]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

# Tensor: 2차원 이상의 임의의 차원의 어레이

In [35]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [36]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [37]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [38]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [39]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [40]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [41]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

[[[(1*9) + (2*11),(1*10)+(2*12), ...]]]

In [42]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [43]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [44]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [45]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

## Autograd 실습
- 파이토치에서 back propagation을 이용해 파라미터를 업데이트 하는 방법
- 일반적으로 gradient descent (GD) 방법으로 알려져 있다
- 아래 예제 코드에서 학습시킬 파라미터는 w1, w2 이다 (requires_grad = True 로 설정)
- 활성화 함수 (비선형 함수)로 clamp()를 사용했다 (ReLU와 유사하나 출력의 최대값을 제한하는 함수)

In [ ]:
import torch

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

x = torch.randn(BATCH_SIZE, 
                INPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)  


y = torch.randn(BATCH_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE,
                dtype = torch.float, 
                requires_grad = False)  

w1 = torch.randn(INPUT_SIZE, 
                 HIDDEN_SIZE, 
                 device = DEVICE, 
                 dtype = torch.float,
                 requires_grad = True)  

w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE, 
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)  

learning_rate = 1e-6                                           
for t in range(1, 501):                                        
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)                    

    loss = (y_pred - y).pow(2).sum()                          
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ", loss.item()) 
    loss.backward()     # back propagation 수행                                      

    with torch.no_grad():   # 그라디언트 값을 고정하고 아래 블록을 수행하라는 뜻                
        w1 -= learning_rate * w1.grad                          
        w2 -= learning_rate * w2.grad                          

        w1.grad.zero_()     # 그라디언트를 새로 계산할 것이므로 초기화를 수행한다                     
        w2.grad.zero_()                                      

Iteration:  100 	 Loss:  758.891845703125
Iteration:  200 	 Loss:  4.890490531921387
Iteration:  300 	 Loss:  0.05182575434446335
Iteration:  400 	 Loss:  0.000969503540545702
Iteration:  500 	 Loss:  9.788053284864873e-05


In [ ]:
# Iteration:  100 	 Loss:  976.0719604492188
# Iteration:  200 	 Loss:  5.061180114746094
# Iteration:  300 	 Loss:  0.04102771729230881
# Iteration:  400 	 Loss:  0.0006718397489748895
# Iteration:  500 	 Loss:  6.94335249136202e-05